apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: pipeline
spec:
  description: A pipeline.
  params:
    - name: repo-url
      type: string
      description: The git repository URL to clone from.
    - name: branch-name
      type: string
      description: The git branch to clone.
  workspaces:
    - name: shared-data
  tasks:
    - name: fetch-repo
      taskRef:
        name: git-clone
      workspaces:
        - name: output
          workspace: shared-data
      params:
        - name: url
          value: $(params.repo-url)
        - name: revision
          value: $(params.branch-name)
    - name: promote-test
      runAfter: ["fetch-repo"]
      taskRef:
        name: promote
      workspaces:
        - name: source
          workspace: shared-data
      params:
        - name: base
          value: test
        - name: head
          value: develop
    - name: promote-production
      runAfter: ["promote-test"]
      taskRef:
        name: promote
      workspaces:
        - name: source
          workspace: shared-data
      params:
        - name: base
          value: master
        - name: head
          value: test